Check for .git in PY files check.
NB: This might cause env.PYFILES checks to fail if they need the var
to at least exist.

diff --git a/.github/workflows/pr-annotate-with-flake8.yml b/.github/workflows/pr-annotate-with-flake8.yml
--- a/.github/workflows/pr-annotate-with-flake8.yml
+++ b/.github/workflows/pr-annotate-with-flake8.yml
@@ -25,8 +25,11 @@ jobs:
         env:
           BASE_REF: ${{github.base_ref}}
         run: |
-          # Will exit with non-zero if no filenames ending in ".py" are in
-          # the diff.
+          # Checkout might not have happened.
+          if [ ! -f ".git" ]; then exit 0 ; fi
+          # Get a list of files ending with ".py", stuff in environment.
+          # We don't rely on exit status because Workflows run with
+          # "set -e" so any failure in a pipe is total failure.
           PYFILES=$(git diff --name-only "refs/remotes/origin/${BASE_REF}" -- | egrep '.py$' || true)
           echo "::set-env name=PYFILES::${PYFILES}"
 
